#Photographs within 200km of Rio de Janeiro
#defaultView:Map

SELECT ?place ?placeLabel ?location
WHERE
{
  # Rio coordinates
  wd:Q8678 wdt:P625 ?rioLoc .
  SERVICE wikibase:around {
    ?place wdt:P625 ?location .
    bd:serviceParam wikibase:center ?rioLoc .
    bd:serviceParam wikibase:radius "200" .
  } .
  # Is an photograph
  FILTER EXISTS { ?place wdt:P31/wdt:P279* wd:Q125191 } .
  
  # In Instituto Moreira Salles collection
  FILTER EXISTS { ?place wdt:P195 wd:Q6041378 } .

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .
  } 
}
