name: Update imagineRio

on:
  repository_dispatch:
    types: [submodule-update]
  workflow_dispatch:
    inputs:
      retile:
        description: "Retile images"
        type: boolean
        required: false
        default: false
      reprocess:
        description: "Reprocess all items"
        type: boolean
        required: false
        default: false
  schedule:
    # Run at 00:00 UTC on the first day of every month
    - cron: "0 0 1 * *"

jobs:
  update-process:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update submodule to latest commit
        run: |
          cd data
          git checkout main
          git pull origin main

      - name: Fetch data using Puppeteer Docker
        env:
          JSTOR_USER: ${{ secrets.JSTOR_USER }}
          JSTOR_PASSWORD: ${{ secrets.JSTOR_PASSWORD }}
          JSTOR_PROJECT: ${{ secrets.JSTOR_PROJECT }}
          JSTOR_VOCABULARY: ${{ secrets.JSTOR_VOCABULARY }}
        run: |
          # Create necessary directories
          mkdir -p data/jstor_download
          
          # Run Puppeteer in Docker
          docker run -i \
            --init \
            --cap-add=SYS_ADMIN \
            -e JSTOR_USER \
            -e JSTOR_PASSWORD \
            -e JSTOR_PROJECT \
            -e JSTOR_VOCABULARY \
            -v $(pwd)/imaginerio-etl:/app/scripts \
            -v $(pwd)/data:/app/data \
            --rm \
            ghcr.io/puppeteer/puppeteer:latest \
            node -e "$(cat scripts/utils/fetchData.js)"

      - name: Build Docker image
        run: docker build . -t etl

      - name: Run Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARCGIS_USER: ${{ secrets.ARCGIS_USER }}
          ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}
          ARCGIS_PORTAL: ${{ secrets.ARCGIS_PORTAL }}
          VIEWCONES_LAYER_URL: ${{ secrets.VIEWCONES_LAYER_URL }}
          RETILE: ${{ github.event.inputs.retile }}
          REPROCESS: ${{ github.event.inputs.reprocess }}
        run: |
          docker run \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_ACCESS_KEY_ID \
            -e ARCGIS_USER \
            -e ARCGIS_PASSWORD \
            -e ARCGIS_PORTAL \
            -e VIEWCONES_LAYER_URL \
            -e RETILE \
            -v $(pwd)/data:/usr/src/app/data \
            etl

      - name: Commit and push changes
        run: |
          cd data
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto updated data" && git push origin HEAD:main || echo "No changes to commit"
          cd ..
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data
          git commit -m "Auto updated submodule reference" && git push || echo "No changes to commit"
